# Generated by Django 4.2.4 on 2023-08-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('ON', 'Turned on'), ('OFF', 'Turned off')], default='OFF', verbose_name='Status')),
                ('pumping_time', models.IntegerField(default=60, verbose_name='Pumping time (s)')),
            ],
            options={
                'verbose_name': 'Pump',
                'verbose_name_plural': 'Pumps',
            },
        ),
    ]
