# Generated by Django 4.2.4 on 2023-08-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watering_system', '0002_alter_pump_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='status',
            field=models.TextField(choices=[('ON', 'Turned on'), ('OFF', 'Turned off'), ('TURNING_ON', 'Turning on'), ('TURNING_OFF', 'Turning off')], default='OFF', verbose_name='Status'),
        ),
    ]
