# Generated by Django 4.2.4 on 2023-08-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('LEFT', 'Left spinning'), ('RIGHT', 'Right spinning'), ('OFF', 'Turned off')], default='OFF', verbose_name='Status')),
                ('left_spinning_time', models.IntegerField(default=60, verbose_name='Left spinning time (s)')),
                ('right_spinning_time', models.IntegerField(default=60, verbose_name='Left spinning time (s)')),
            ],
            options={
                'verbose_name': 'Motor',
                'verbose_name_plural': 'Motors',
            },
        ),
    ]
