# Generated by Django 4.2.4 on 2023-08-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_opener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='door_status',
            field=models.TextField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('OPENING', 'Opening'), ('CLOSING', 'Closing')], default='OPEN', verbose_name='Door status'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='status',
            field=models.TextField(choices=[('LEFT', 'Closing'), ('RIGHT', 'Opening'), ('OFF', 'Turned off'), ('TURNING_ON', 'Turning on'), ('TURNING_OFF', 'Turning off')], default='OFF', verbose_name='Status'),
        ),
    ]
